### ISSUE TITLE
extra_args example

### ISSUE THREAD

**Issue by atassis** [aevea/action-kaniko#17]
It would be nice to provide examples of `extra_args` usage approaches

**Comment by cbtum** [comment]
Has anyone figured out how to use `extra_args`? Currently, I have no idea how to use it and without these `extra_args`, I am not able to use action-kaniko

**Comment by sandromodarelli** [comment]
here's an example of how `extra_args` works:

```
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        image: quay.io/sandromodarelli/image
        tag: 1.0.0
        registry: quay.io
        username: ${{ secrets.QUAYIO_ACCESS_USERNAME }}
        password: ${{ secrets.QUAYIO_ACCESS_PASSWORD }}
        extra_args: --build-arg SECRET_USER=${{ secrets.SECRET_USER }} --build-arg SECRET_TOKEN=${{ secrets.SECRET_TOKEN }}
```

i'm using this to build a `Dockerfile` like:
```
FROM python:3.6-alpine
ARG SECRET_USER
ARG SECRET_TOKEN
...
```
