### ISSUE TITLE
File not found: 'docker' error

### ISSUE THREAD

**Issue by jakub-przybyla** [aevea/action-kaniko#19]
I tried to build a docker image and sent it to ACR registry (secrets to ACR stored in previous action step), but when comes to Kaniko builder the error occurs:
```
Build container for action use: '/home/runner/_work/_actions/aevea/action-kaniko/v0.6.0/Dockerfile'.
Error: File not found: 'docker'
```

![image](https://user-images.githubusercontent.com/81560416/112818888-4ef9ab00-9084-11eb-8588-ce2cff7fde3b.png)

error is the same no matter what "path" parameter I will use (I tried docker/base, ./docker and also /mnt/gh_actions/DevOps/DevOps/docker, which is place where I have my Dockerfile).
code of the step is like this:

```
jobs:  
  docker:
    runs-on: [self-hosted-DevOps-master-centos]
    needs: [build-cm-package]
    steps:

    - name: Kaniko builder
      uses: aevea/action-kaniko@v0.6.0
      with:     
        path: ${{ env.docker_repository_folder }}/base
        build_file: base/Dockerfile
        registry: ${{ env.REGISTRY_LOGIN_SERVER }}
        image: kaniko_test
        username: ${{ secrets.ACR_DEV_USERNAME }}
        password: ${{ secrets.ACR_DEV_USERNAME_PASSWORD }}
        cache: true
        cache_registry: aevea/cache
```
any hint what is wrong?
