### ISSUE TITLE
Auth does not work with docker-login action.

### ISSUE THREAD

**Issue by andaag** [aevea/action-kaniko#43]
I use the following to auth to GCR:
```
    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
```

This works fine in combination with 
```
    - name: Build container
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
```
However, it doesn't work with kaniko, as that requires a username/password.

I'm using federated authentication, so I don't generate any passwords at all in this setup.
