### ISSUE TITLE
Build context

### ISSUE THREAD

**Issue by hadim** [aevea/action-kaniko#7]
My repo contains multiple image files. I specify the `Dockerfile` with:

```
build_file: conda/Dockerfile
```

but the context is still set to the root of the repo.

Could you add an option to set the context dir?

**Comment by somdoron** [comment]
I think you can use working-directory for that

**Comment by somdoron** [comment]
I think you can use working-directory for that

**Comment by hadim** [comment]
`working-directory` cannot be used for individual steps with existing actions for what I understand. The second image I build depend on the previous one and so I must have it in the `steps` (it also avoid code duplication about checking out).

```yaml
name: Build and Push Docker Images

env:
  PROJECT_ID: my-project

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@0.2
        with:
          account_key: ${{ secrets.GCR_PUSH_KEY_BASE64 }}

      - name: Build my-image-base
        uses: aevea/action-kaniko@v0.4.0
        with:
          image: ${{ env.PROJECT_ID }}/my-image-base
          build_file: base/Dockerfile
          registry: gcr.io
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          tag: true
          # cache: true
          # cache_registry: gcr.io
          skip_unchanged_digest: true
          # build_args: BASE_IMAGE=ubuntu:20.04,BUILDKIT_INLINE_CACHE=1

      - name: Build my-image
        uses: aevea/action-kaniko@v0.4.0
        with:
          image: ${{ env.PROJECT_ID }}/my-image
          build_file: image/Dockerfile
          registry: gcr.io
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          tag: true
          # cache: true
          # cache_registry: gcr.io
          skip_unchanged_digest: true
          # build_args: BASE_IMAGE=ubuntu:20.04,BUILDKIT_INLINE_CACHE=1
```

So unless I am missing something this `working-directory` feature can only work if set at the `action-kaniko` level: https://github.com/aevea/action-kaniko/blob/master/entrypoint.sh#L46
